#!/usr/bin/env python3
#
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import pathlib
import subprocess
import sys

scriptdir = pathlib.Path(__file__).parent
sys.path.append(str(scriptdir / "python"))

import fetchhash

def parse_args():
    p = argparse.ArgumentParser(allow_abbrev=False)
    return p.parse_args()

def main():
    args = parse_args()
    build = scriptdir / "build"
    fetch = build / "fetch"
    fetch.mkdir(parents = True, exist_ok = True)

    latexrun = build / "latexrun"
    if not latexrun.is_file():
        fl = fetch / "latexrun"
        fetchhash.fetch_file(fl,
            "https://raw.githubusercontent.com/aclements/latexrun/38ff6ec2815654513c91f64bdf2a5760c85da26e/latexrun",
            "2f144fc6257da7d47475165d2599ecb779d48ca25eb88c5bca4fbc9468a34782")
        fl.chmod(0o755)
        fl.rename(latexrun)

    subprocess.run([str(latexrun),
            "-o", "cardchoose.pdf",
            "-O", str(build / "latex.out"),
            "--latex-cmd", "lualatex",
            "--latex-args=-shell-escape",
            "--bibtex-cmd", "biber",
            "cardchoose.tex"],
        cwd=scriptdir, check=True)

if __name__ == "__main__":
    main()
