#!/usr/bin/env python3

# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import pathlib

import plot_anim
import read_results

topdir = pathlib.Path(__file__).resolve().parent.parent

def parse_args():
    p = argparse.ArgumentParser(allow_abbrev=False)
    return p.parse_args()

def main():
    args = parse_args()
    results = topdir / "results/latest"
    all_algorithms, data = read_results.read_for_plot(results / "random.csv")
    plot_anim.plot(all_algorithms, data, "Random order", results / "random.webp")
    for n in [1346269, 701408733]:
        plot_anim.plot(all_algorithms, [d for d in data if d[0] == n],
            "Random order", topdir / "latex" / f"random_{n}.pgf")
    all_algorithms, data = read_results.read_for_plot(results / "sorted.csv")
    plot_anim.plot(all_algorithms, data, "Sorted order", results / "sorted.webp")

if __name__ == '__main__':
    main()
