#!/usr/bin/env python3

# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import pathlib

import plot_anim
import read_results

topdir = pathlib.Path(__file__).resolve().parent.parent

def parse_args():
    p = argparse.ArgumentParser(allow_abbrev=False,
        description="Plot all algorithms")
    p.add_argument('title')
    p.add_argument('csv', type=pathlib.Path)
    p.add_argument("--algorithm",  action='append')
    p.add_argument('--output')
    p.add_argument('--n', type=int)
    return p.parse_args()

def main():
    args = parse_args()
    data = {}
    for item in read_results.read(args.csv):
        if item.k != 0:
            data.setdefault(item.n, {}).setdefault(item.alg, []).append((item.k, 1E9 * item.time/item.k))
    all_algorithms = set()
    for nv in data.values():
        for alg, d in nv.items():
            d.sort()
            all_algorithms.add(alg)
    if args.algorithm is None:
        args.algorithm = list(sorted(all_algorithms))
    if args.n is None:
        nvalues = list(sorted(data.keys()))
        print(nvalues)
    else:
        nvalues = [args.n]
    data = [(n, data[n]) for n in nvalues]
    plot_anim.plot(args.algorithm, data, args.title, args.output)

if __name__ == '__main__':
    main()
